#env:
#  global:
#    - FRAMEWORK_NAME=Noonian

script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681
matrix:
  include:
    - script:
        - carthage bootstrap 
        - set -o pipefail && xcodebuild -scheme Noonian -project Noonian.xcodeproj clean build test | xcpretty
      env: JOB=Xcode
      os: osx
      osx_image: xcode8
      language: objective-c
      before_install:
        - ./scripts/upstall-carthage.sh
        - ./scripts/upstall-swiftlint.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
#      before_deploy:
#        - carthage build --no-skip-current
#        - carthage archive $FRAMEWORK_NAME
    - script:
        - swift build
        - swift test
      env: JOB=SPM
      os: osx
      osx_image: xcode8
      language: objective-c
    - script:
        - swift build
        - swift test
      env: JOB=Linux
      sudo: required
      dist: trusty
      language: generic
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
        - export SWIFT_SNAPSHOT=swift-3.0.1-GM-CANDIDATE
        - export SWIFT_URL=https://swift.org/builds/$SWIFT_SNAPSHOT/ubuntu1404/$SWIFT_SNAPSHOT/$SWIFT_SNAPSHOT-ubuntu14.04.tar.gz
        - wget $SWIFT_URL
        - wget $SWIFT_URL.sig
        - gpg --verify $SWIFT_SNAPSHOT-ubuntu14.04.tar.gz.sig
        - tar xzf $SWIFT_SNAPSHOT-ubuntu14.04.tar.gz
        - export PATH="${PWD}/${SWIFT_SNAPSHOT}-ubuntu14.04/usr/bin:${PATH}"
        - cd Noonian

  exclude:
    - script: placeholder # workaround for https://github.com/travis-ci/travis-ci/issues/4681

#deploy:
#  provider: releases
#  api_key:
#    secure: CLgRTCkr9FXlDS9bTejaSCUN78lT110kyFXsod+LAGZo/zqzebVwo/XTqSIdHV6raWP+KsazUNyt4YhjZgaLG2CCf+MZVY2yelnuE419/rgSqW2FrVkcMqhIc+vFAp57qK/E8mC5GnZO35uhxZ0CM98h75G7pL2ebWu/WmB9zV3nujNl1mTXRIMD9SRihjzM+RjyrNAPZyqvVkFM4nJBUTA3jW+QsbqcNy7ds1Erz/kFsuBHCTbbYaqq+W7vZAL7NQlaqfpcN1jSxh0PuaEjLicCMqzDpkd0ODeu1F0r9Ql/9Nf7QiWv8BusBdwBqee2p+ET7h2hXYXzkNYkVCz1Gp8twviXcQNyfM3h8lhqcvsYPcjXIWEHzwgNsUlltFH62//JqlJegU17p2WniJXtHNHsjcEnjC1ngLix+IBSv9z1uJPYGisSA4AwLjiiEQc8UhRNT8DOmrVmRcODIU8PMfJPiwmA8eBpVb6bwD/zwMDtH3E40gO1qTIvz496I0VT+81GfDYv0xfHcER++OBpCNjLnnInTFCDmF8XaPR14jusCyWbAeL5pGb4K6HcwYPWM5g27/2yaUNY7haI1BFi/p/apQ9sFzWeHJ0BG3hwNUPrLwIsqTyXZm5Q/OuDeaHa7Ye9qbJtO281m09a2qWEmBx/fZHQuT4eNbe1W/xoWcA=
#  file: $FRAMEWORK_NAME.framework.zip
#  skip_cleanup: true
#  on:
#    repo: scottrhoyt/Noonian
#    tags: true
#    condition: $JOB = Xcode
